
import java.awt.Color;
import java.awt.Image;
import java.lang.Math.*;
import java.util.ArrayList;
import java.util.Random;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class play_games extends javax.swing.JFrame {
MatteBorder gray_b1=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.DARK_GRAY);
MatteBorder orange_b2=BorderFactory.createMatteBorder(2,2, 2, 2, Color.ORANGE);

String stones="/Images/stone.jpg";
String papers="/Images/paper.jpg";
String scissors="/Images/scissor.jpg";
ArrayList<String>list =new ArrayList<>();
Random random=new Random();
int you_win=0;
int computer_win=0;
String random_selection;
  
    public play_games() {
        initComponents();
        You.setBorder(gray_b1);
                computer.setBorder(gray_b1);
        rock.setBorder(gray_b1);
       paper.setBorder(gray_b1);
        scissor.setBorder(gray_b1);
        displayimage(stones,rock);
        displayimage(papers,paper);
        displayimage(scissors,scissor);
        list.add(stones);
           list.add(papers);
        list.add(scissors);

    }public void displayimage(String imagepath,JLabel label){
        ImageIcon icon1 =new ImageIcon(getClass().getResource(imagepath));
        
        
        Image img1=icon1.getImage().getScaledInstance(label.getWidth(),label.getHeight(),Image.SCALE_SMOOTH);
        
        
        label.setIcon(new ImageIcon(img1));
       
        
        
    }
    public void getWinner(String you ,String Computer){
        if(Computer.equals(you)){
            System.out.println("Draw");
            
        }
        
        else if(you.equals(stones)){
            if(Computer.equals(scissors)){
                you_win++;
                youscore.setText(String.valueOf(you_win));
                
            }
            else if(Computer.equals(papers)){
                computer_win++;
                computerscore.setText(String.valueOf(computer_win));
            }
           
        }
        else if(you.equals(papers)){
            if(Computer.equals(stones)){
                you_win++;
                youscore.setText(String.valueOf(you_win));
                
            }
            else if(Computer.equals(scissors)){
                computer_win++;
                computerscore.setText(String.valueOf(computer_win));
            }
        }
        else if(you.equals(scissors)){
            if(Computer.equals(papers)){
                you_win++;
                youscore.setText(String.valueOf(you_win));
                
            }
            else if(Computer.equals(stones)){
                computer_win++;
                computerscore.setText(String.valueOf(computer_win));
            }
        }
        if(you_win==3||computer_win==3){
            int yes_no=JOptionPane.showConfirmDialog(null,"play again","play again",JOptionPane.YES_NO_OPTION);
            if(yes_no==0){
            computer.setIcon(null);
//            
//you.setIcon(null);
You.setIcon(null);
            you_win=0;
            computer_win=0;
            computerscore.setText(String.valueOf(computer_win));
             youscore.setText(String.valueOf(you_win));
            }
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        computer = new javax.swing.JLabel();
        paper = new javax.swing.JLabel();
        youscore = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        computerscore = new javax.swing.JLabel();
        You = new javax.swing.JLabel();
        scissor = new javax.swing.JLabel();
        rock = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        computer.setBackground(new java.awt.Color(204, 0, 204));
        computer.setOpaque(true);

        paper.setBackground(new java.awt.Color(204, 0, 204));
        paper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paper.setOpaque(true);
        paper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paperMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paperMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paperMouseExited(evt);
            }
        });

        youscore.setBackground(new java.awt.Color(0, 204, 0));
        youscore.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        youscore.setForeground(new java.awt.Color(0, 204, 51));
        youscore.setText("0");

        jLabel4.setBackground(new java.awt.Color(0, 204, 0));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("-");

        computerscore.setBackground(new java.awt.Color(0, 204, 0));
        computerscore.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        computerscore.setForeground(new java.awt.Color(255, 51, 51));
        computerscore.setText("0");

        You.setBackground(new java.awt.Color(204, 0, 204));
        You.setOpaque(true);

        scissor.setBackground(new java.awt.Color(204, 0, 204));
        scissor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scissor.setOpaque(true);
        scissor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scissorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scissorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scissorMouseExited(evt);
            }
        });

        rock.setBackground(new java.awt.Color(204, 0, 204));
        rock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rock.setOpaque(true);
        rock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rockMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("COMPUTER");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("YOU");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(youscore)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(computerscore)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scissor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(computer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(You, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(computer, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(youscore, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(computerscore, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paper, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(scissor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(You, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockMouseClicked
        // TODO add your handling code here:
        displayimage(stones,You);
        random_selection=list.get(random.nextInt(list.size()));
                displayimage(random_selection,computer);
                getWinner(stones,random_selection);

        
        
    }//GEN-LAST:event_rockMouseClicked

    private void paperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paperMouseClicked
        // TODO add your handling code here:
                        displayimage(papers,You);
                         random_selection=list.get(random.nextInt(list.size()));
                displayimage(random_selection,computer);
                                getWinner(papers,random_selection);



    }//GEN-LAST:event_paperMouseClicked

    private void scissorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scissorMouseClicked
        // TODO add your handling code here:
                        displayimage(scissors,You);
                         random_selection=list.get(random.nextInt(list.size()));
                displayimage(random_selection,computer);
                                getWinner(scissors,random_selection);



    }//GEN-LAST:event_scissorMouseClicked

    private void rockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockMouseEntered
        // TODO add your handling code here:
        rock.setBorder(orange_b2);

    }//GEN-LAST:event_rockMouseEntered

    private void paperMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paperMouseEntered
        // TODO add your handling code here:
                paper.setBorder(orange_b2);

    }//GEN-LAST:event_paperMouseEntered

    private void scissorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scissorMouseEntered
        // TODO add your handling code here:
                scissor.setBorder(orange_b2);

    }//GEN-LAST:event_scissorMouseEntered

    private void rockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockMouseExited
        // TODO add your handling code here:
                        rock.setBorder(gray_b1);

    }//GEN-LAST:event_rockMouseExited

    private void paperMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paperMouseExited
        // TODO add your handling code here:
                                paper.setBorder(gray_b1);

    }//GEN-LAST:event_paperMouseExited

    private void scissorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scissorMouseExited
        // TODO add your handling code here:
                                scissor.setBorder(gray_b1);

    }//GEN-LAST:event_scissorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(play_games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(play_games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(play_games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(play_games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new play_games().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel You;
    private javax.swing.JLabel computer;
    private javax.swing.JLabel computerscore;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel paper;
    private javax.swing.JLabel rock;
    private javax.swing.JLabel scissor;
    private javax.swing.JLabel youscore;
    // End of variables declaration//GEN-END:variables
}
